// Reads price-sheet.csv and writes src/data/sheet.generated.ts
// Columns: slug, name, category, price_kes, price_type (from or fixed), description
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

if (!existsSync('price-sheet.csv')) {
  console.log('price-sheet.csv not found in the project root.');
  process.exit(1);
}

let text = readFileSync('price-sheet.csv', 'utf8').replace(/^\uFEFF/, '');
const firstLine = text.split(/\r?\n/)[0] || '';
const delim = firstLine.includes(',') ? ',' : firstLine.includes(';') ? ';' : ',';

function parse(src) {
  const rows = [];
  let row = [], cur = '', q = false;
  for (let i = 0; i < src.length; i++) {
    const ch = src[i];
    if (q) {
      if (ch === '"') { if (src[i + 1] === '"') { cur += '"'; i++; } else q = false; }
      else cur += ch;
    } else if (ch === '"') q = true;
    else if (ch === delim) { row.push(cur); cur = ''; }
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && src[i + 1] === '\n') i++;
      row.push(cur); cur = ''; rows.push(row); row = [];
    } else cur += ch;
  }
  if (cur !== '' || row.length) { row.push(cur); rows.push(row); }
  return rows;
}

const rows = parse(text).filter((r) => r.some((x) => x.trim() !== ''));
const head = rows.shift().map((h) => h.trim().toLowerCase());
const col = (n) => head.indexOf(n);
const iSlug = col('slug'), iPrice = col('price_kes'), iType = col('price_type'), iDesc = col('description');
if (iSlug < 0 || iPrice < 0) { console.log('The CSV needs the columns slug and price_kes.'); process.exit(1); }

const prices = {}, descs = {}, problems = [];
for (const r of rows) {
  const slug = (r[iSlug] || '').trim();
  if (!slug) continue;
  const rawPrice = (r[iPrice] || '').replace(/kes/i, '').replace(/[,\s]/g, '');
  if (rawPrice !== '') {
    const n = Number(rawPrice);
    if (isFinite(n) && n > 0) {
      const t = (iType >= 0 ? (r[iType] || '').trim().toLowerCase() : 'from') === 'fixed' ? 'fixed' : 'from';
      prices[slug] = { type: t, amount: Math.round(n) };
    } else problems.push(`${slug}: "${r[iPrice]}" is not a valid price`);
  }
  const d = iDesc >= 0 ? (r[iDesc] || '').trim() : '';
  if (d) descs[slug] = d;
}

const out =
  '// Generated by scripts/import-prices.mjs from price-sheet.csv. Do not edit by hand.\n' +
  "export const SHEET_PRICES: Record<string, { type: 'fixed' | 'from'; amount: number }> = " + JSON.stringify(prices, null, 2) + ';\n' +
  'export const SHEET_DESC: Record<string, string> = ' + JSON.stringify(descs, null, 2) + ';\n';
writeFileSync('src/data/sheet.generated.ts', out);

console.log(`Prices loaded: ${Object.keys(prices).length}`);
console.log(`Descriptions loaded: ${Object.keys(descs).length}`);
if (problems.length) { console.log('Check these rows:'); problems.forEach((p) => console.log('  ' + p)); }