// Generated by scripts/import-prices.mjs from price-sheet.csv. Do not edit by hand.
export const SHEET_PRICES: Record<string, { type: 'fixed' | 'from'; amount: number }> = {
  "business-cards": {
    "type": "from",
    "amount": 12
  },
  "letterheads": {
    "type": "from",
    "amount": 20
  },
  "envelopes": {
    "type": "from",
    "amount": 25
  },
  "receipt-books": {
    "type": "from",
    "amount": 350
  },
  "presentation-folders": {
    "type": "from",
    "amount": 150
  },
  "certificates": {
    "type": "from",
    "amount": 80
  },
  "corporate-stationery": {
    "type": "from",
    "amount": 500
  },
  "gift-vouchers": {
    "type": "from",
    "amount": 60
  },
  "bookmarks": {
    "type": "from",
    "amount": 19
  },
  "postcards": {
    "type": "from",
    "amount": 25
  },
  "flyers": {
    "type": "from",
    "amount": 20
  },
  "posters": {
    "type": "from",
    "amount": 300
  },
  "brochures": {
    "type": "from",
    "amount": 60
  },
  "menus": {
    "type": "from",
    "amount": 600
  },
  "programmes": {
    "type": "from",
    "amount": 100
  },
  "x-banners": {
    "type": "from",
    "amount": 4500
  },
  "roll-up-banners": {
    "type": "from",
    "amount": 8500
  },
  "l-banners": {
    "type": "from",
    "amount": 3500
  },
  "backdrops": {
    "type": "from",
    "amount": 27000
  },
  "media-walls": {
    "type": "from",
    "amount": 30000
  },
  "vinyl-banners": {
    "type": "from",
    "amount": 1200
  },
  "large-format-printing": {
    "type": "from",
    "amount": 800
  },
  "wheel-cover-printing": {
    "type": "from",
    "amount": 5500
  },
  "other-large-format-materials": {
    "type": "from",
    "amount": 1500
  },
  "wedding-cards": {
    "type": "from",
    "amount": 80
  },
  "invitation-cards": {
    "type": "from",
    "amount": 50
  },
  "funeral-programmes": {
    "type": "from",
    "amount": 150
  },
  "event-programmes": {
    "type": "from",
    "amount": 100
  },
  "new-baby-cards": {
    "type": "from",
    "amount": 35
  },
  "name-tags": {
    "type": "from",
    "amount": 80
  },
  "tent-cards": {
    "type": "from",
    "amount": 60
  },
  "table-materials": {
    "type": "from",
    "amount": 200
  },
  "event-display-materials": {
    "type": "from",
    "amount": 2500
  },
  "branded-t-shirts": {
    "type": "from",
    "amount": 1000
  },
  "polo-shirts": {
    "type": "from",
    "amount": 1200
  },
  "hoodies": {
    "type": "from",
    "amount": 2700
  },
  "jerseys": {
    "type": "from",
    "amount": 1492
  },
  "caps": {
    "type": "from",
    "amount": 600
  },
  "aprons": {
    "type": "from",
    "amount": 900
  },
  "reflector-jackets": {
    "type": "from",
    "amount": 380
  },
  "other-wearable-branding": {
    "type": "from",
    "amount": 1000
  },
  "stickers": {
    "type": "from",
    "amount": 4
  },
  "product-labels": {
    "type": "from",
    "amount": 5
  },
  "vinyl-stickers": {
    "type": "from",
    "amount": 30
  },
  "reflective-stickers": {
    "type": "from",
    "amount": 150
  },
  "floor-stickers": {
    "type": "from",
    "amount": 600
  },
  "car-stickers": {
    "type": "from",
    "amount": 1260
  },
  "bike-stickers": {
    "type": "from",
    "amount": 300
  },
  "custom-labels": {
    "type": "from",
    "amount": 5
  },
  "door-signs": {
    "type": "from",
    "amount": 800
  },
  "door-plates": {
    "type": "from",
    "amount": 1250
  },
  "rigid-signs": {
    "type": "from",
    "amount": 3500
  },
  "3d-signs": {
    "type": "from",
    "amount": 6000
  },
  "printed-signs": {
    "type": "from",
    "amount": 1500
  },
  "business-signage": {
    "type": "from",
    "amount": 8000
  },
  "custom-signage": {
    "type": "from",
    "amount": 5000
  },
  "branded-pens": {
    "type": "from",
    "amount": 80
  },
  "keyholders": {
    "type": "from",
    "amount": 150
  },
  "mousepads": {
    "type": "from",
    "amount": 450
  },
  "tote-bags": {
    "type": "from",
    "amount": 400
  },
  "drawstring-bags": {
    "type": "from",
    "amount": 250
  },
  "umbrellas": {
    "type": "from",
    "amount": 900
  },
  "promotional-merchandise": {
    "type": "from",
    "amount": 500
  },
  "branded-mugs": {
    "type": "from",
    "amount": 420
  },
  "enamel-mugs": {
    "type": "from",
    "amount": 850
  },
  "thermal-mugs": {
    "type": "from",
    "amount": 1300
  },
  "flasks": {
    "type": "from",
    "amount": 1500
  },
  "water-bottles": {
    "type": "from",
    "amount": 850
  },
  "other-branded-drinkware": {
    "type": "from",
    "amount": 700
  },
  "kraft-bags": {
    "type": "from",
    "amount": 150
  },
  "jute-bags": {
    "type": "from",
    "amount": 1250
  },
  "branded-bags": {
    "type": "from",
    "amount": 200
  },
  "packaging-boxes": {
    "type": "from",
    "amount": 45
  },
  "product-packaging": {
    "type": "from",
    "amount": 100
  },
  "photo-printing": {
    "type": "from",
    "amount": 25
  },
  "passport-photos": {
    "type": "fixed",
    "amount": 150
  },
  "mounted-photos": {
    "type": "from",
    "amount": 796
  },
  "photo-framing": {
    "type": "from",
    "amount": 1600
  },
  "canvas-printing": {
    "type": "from",
    "amount": 5500
  },
  "book-printing": {
    "type": "from",
    "amount": 500
  },
  "booklets": {
    "type": "from",
    "amount": 200
  },
  "magazines": {
    "type": "from",
    "amount": 300
  },
  "catalogues": {
    "type": "from",
    "amount": 250
  },
  "spiral-binding": {
    "type": "from",
    "amount": 150
  },
  "binding-finishing": {
    "type": "from",
    "amount": 200
  },
  "calendars": {
    "type": "from",
    "amount": 350
  },
  "diaries": {
    "type": "from",
    "amount": 600
  },
  "notebooks": {
    "type": "from",
    "amount": 250
  },
  "planners": {
    "type": "from",
    "amount": 950
  },
  "custom-stationery": {
    "type": "from",
    "amount": 500
  },
  "document-printing": {
    "type": "from",
    "amount": 10
  },
  "photocopying": {
    "type": "from",
    "amount": 5
  },
  "typesetting": {
    "type": "from",
    "amount": 200
  },
  "scanning": {
    "type": "from",
    "amount": 20
  },
  "binding": {
    "type": "from",
    "amount": 150
  },
  "lamination": {
    "type": "from",
    "amount": 30
  },
  "computer-services": {
    "type": "from",
    "amount": 100
  },
  "cyber-services": {
    "type": "from",
    "amount": 50
  },
  "logo-design": {
    "type": "from",
    "amount": 3000
  },
  "business-material-design": {
    "type": "from",
    "amount": 1500
  },
  "poster-design": {
    "type": "from",
    "amount": 1000
  },
  "flyer-design": {
    "type": "from",
    "amount": 800
  },
  "invitation-design": {
    "type": "from",
    "amount": 1000
  },
  "social-media-graphics": {
    "type": "from",
    "amount": 500
  },
  "other-graphic-design-services": {
    "type": "from",
    "amount": 500
  }
};
export const SHEET_DESC: Record<string, string> = {};
